services:
  findfi-api:
    image: findfi-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DB1=Server=mysql-db;Port=3306;Database=rent_core;User ID=root;Password=12345678;SslMode=None;
    depends_on:
      mysql-db:
        condition: service_healthy

  mysql-db:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=rent_core
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
